name: CI with Cache
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: prime-cache-73303f3
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: cache-73303f3



